version: "3.7"

services:

  cql-results:
    stdin_open: true
    container_name: cql-results
    build: .
    ports:
      - "3030:3000"
    volumes:
      - /app/node_modules
      - .:/app
      - ./src/data:/app/src/data
